//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int Codigo { get; set; }
        public int Numero { get; set; }
        public int CodigoInmueble { get; set; }
        public int Cantidad { get; set; }
        public double ValorUnitario { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Inmueble Inmueble { get; set; }
    }
}
