//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBInmobiliariaEntities : DbContext
    {
        public DBInmobiliariaEntities()
            : base("name=DBInmobiliariaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arriendo> Arriendoes { get; set; }
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<Ciudad> Ciudads { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Comision> Comisions { get; set; }
        public virtual DbSet<Contrato> Contratoes { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<EmpleadoCargo> EmpleadoCargoes { get; set; }
        public virtual DbSet<Estado> Estadoes { get; set; }
        public virtual DbSet<FormaPago> FormaPagoes { get; set; }
        public virtual DbSet<Inmueble> Inmuebles { get; set; }
        public virtual DbSet<Pai> Pais { get; set; }
        public virtual DbSet<Queja> Quejas { get; set; }
        public virtual DbSet<TipoInmueble> TipoInmuebles { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
        public virtual DbSet<Visita> Visitas { get; set; }
    }
}
